name: ghcr_clean

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  ghcr_clean:
    name: ghcr_clean
    runs-on: ubuntu-latest
    steps:
      - name: Delete old containers
        uses: snok/container-retention-policy@v2
        with:
          image-names: '*'
          cut-off: now UTC
          account-type: personal
          untagged-only: true
          token: ${{ secrets.GHCR_TOKEN }}
